#!/usr/bin/env python3
"""Launcher: ./lem-in < map | ./visu-hex"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from visu_hex.__main__ import main  # noqa: E402

if __name__ == '__main__':
    sys.exit(main())
